package com.studienfaecher;

public enum Fach {
    ARCHITEKTURSTUDIUM, BIOLOGIESTUDIUM, GERMANISTIKSTUDIUM,
    GESCHICHTSSTUDIUM, INFORMATIKSTUDIUM, MATHEMATIKSTUDIUM,
    PHYSIKSTUDIUM, POLITOLOGIESTUDIUM, WIRTSCHAFTLICHESSTUDIUM;

}
